"""add user profiles

Revision ID: 9993b88fad9a
Revises: 657d9e32a191
Create Date: 2026-09-30 13:42:54.252652
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9993b88fad9a"
down_revision: Union[str, Sequence[str], None] = "657d9e32a191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create user profiles and migrate existing profile data."""

    # 1. Create the new user_profiles table.
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("profile_photo_url", sa.Text(), nullable=True),
        sa.Column(
            "profile_visibility",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "books_visibility",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "vinyl_visibility",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. Enforce one profile per user.
    op.create_index(
        op.f("ix_user_profiles_user_id"),
        "user_profiles",
        ["user_id"],
        unique=True,
    )

    # 3. Create a profile for every existing user and preserve their bio.
    #
    # gen_random_uuid() is generated by PostgreSQL. We cast it to text
    # because MyBookNook currently stores UUIDs as VARCHAR(36).
    op.execute(
        """
        INSERT INTO user_profiles (
            id,
            user_id,
            display_name,
            bio,
            profile_photo_url,
            profile_visibility,
            books_visibility,
            vinyl_visibility,
            created_at,
            updated_at
        )
        SELECT
            gen_random_uuid()::text,
            id,
            username,
            bio,
            NULL,
            'public',
            'private',
            'private',
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        FROM users
        """
    )

    # 4. Bio data now lives in user_profiles, so remove the old column.
    op.drop_column("users", "bio")


def downgrade() -> None:
    """Restore the previous user schema without losing bio data."""

    # 1. Restore the old bio column temporarily as nullable.
    op.add_column(
        "users",
        sa.Column(
            "bio",
            sa.Text(),
            nullable=True,
        ),
    )

    # 2. Copy profile bios back to users.
    op.execute(
        """
        UPDATE users
        SET bio = user_profiles.bio
        FROM user_profiles
        WHERE user_profiles.user_id = users.id
        """
    )

    # 3. Protect against any user that somehow has no profile.
    op.execute(
        """
        UPDATE users
        SET bio = ''
        WHERE bio IS NULL
        """
    )

    # 4. Restore the original NOT NULL requirement.
    op.alter_column(
        "users",
        "bio",
        nullable=False,
    )

    # 5. Remove the profile infrastructure.
    op.drop_index(
        op.f("ix_user_profiles_user_id"),
        table_name="user_profiles",
    )

    op.drop_table("user_profiles")